/* CoachFlow Mobile 2.0 — navegação compacta, safe-area e seções recolhíveis */
(function(){
'use strict';
const MOBILE='(max-width: 760px)';
function isMobile(){return matchMedia(MOBILE).matches}
function addCss(){if(document.getElementById('cfMobile2Style'))return;const s=document.createElement('style');s.id='cfMobile2Style';s.textContent=`
:root{--cfm-bg:#f7f4f1;--cfm-card:#fff;--cfm-ink:#201712;--cfm-muted:#786b63;--cfm-accent:#f45b2a;--cfm-line:#e9dfd8;--cfm-green:#237a4b}
#cfMobileNav,#cfMobileSheet,#cfMobileBackdrop{display:none}
@media(max-width:760px){
html{background:var(--cfm-bg)}body{padding-bottom:calc(78px + env(safe-area-inset-bottom));overflow-x:hidden;background:var(--cfm-bg)!important;-webkit-tap-highlight-color:transparent}body>*{max-width:100vw}.container,.wrap,.app,.shell,main{max-width:100%!important}.container,.wrap,main{padding-left:12px!important;padding-right:12px!important}
/* menu desktop vira secundário; a barra inferior assume a navegação */
nav.tabs,.tabs,.tabbar,[role="tablist"]{scrollbar-width:none}.tabs::-webkit-scrollbar,.tabbar::-webkit-scrollbar{display:none}
#cfMobileNav{position:fixed;display:grid;grid-template-columns:repeat(5,1fr);left:8px;right:8px;bottom:calc(8px + env(safe-area-inset-bottom));z-index:9998;background:rgba(255,255,255,.96);border:1px solid rgba(222,211,203,.92);box-shadow:0 10px 34px rgba(55,35,25,.16);border-radius:19px;padding:6px 5px;backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
.cfmNavBtn{appearance:none;border:0!important;background:transparent!important;color:#786b63!important;min-width:0!important;min-height:54px!important;padding:5px 2px!important;border-radius:14px!important;display:flex!important;flex-direction:column;align-items:center;justify-content:center;gap:3px;font:700 10px/1.1 system-ui,-apple-system,sans-serif!important;box-shadow:none!important}.cfmNavBtn svg{width:20px;height:20px;stroke:currentColor;stroke-width:1.9;fill:none}.cfmNavBtn.active{background:#fff1eb!important;color:#d94d20!important}.cfmNavBtn:active{transform:scale(.97)}
#cfMobileBackdrop{position:fixed;display:block;inset:0;z-index:9998;background:rgba(30,20,15,.32);opacity:0;pointer-events:none;transition:.2s}#cfMobileBackdrop.open{opacity:1;pointer-events:auto}
#cfMobileSheet{position:fixed;display:block;left:8px;right:8px;bottom:calc(8px + env(safe-area-inset-bottom));z-index:9999;background:#fff;border:1px solid var(--cfm-line);border-radius:24px;padding:9px 14px 18px;box-shadow:0 24px 70px rgba(40,25,18,.28);transform:translateY(calc(100% + 30px));transition:transform .25s ease;max-height:78vh;overflow:auto}#cfMobileSheet.open{transform:translateY(0)}.cfmGrab{width:42px;height:5px;background:#ded7d2;border-radius:999px;margin:1px auto 14px}.cfmSheetHead{display:flex;justify-content:space-between;align-items:center;margin:0 2px 12px}.cfmSheetHead strong{font-size:18px;color:var(--cfm-ink)}.cfmClose{border:0!important;background:#f5f1ee!important;border-radius:10px!important;width:38px;height:38px;padding:0!important;font-size:18px!important}.cfmSheetGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.cfmMore{border:1px solid var(--cfm-line)!important;background:#fff!important;color:var(--cfm-ink)!important;border-radius:14px!important;min-height:64px;padding:10px 12px!important;text-align:left;font-weight:750!important;font-size:13px!important;display:flex;align-items:center;gap:9px}.cfmMore span{font-size:20px}
/* Home 2.0 mobile */
.cfHome2{margin-top:2px!important}.cfHome2Head{margin:0 0 10px!important;display:grid!important;grid-template-columns:1fr auto!important;align-items:center!important;gap:8px!important}.cfHome2Head h2{font-size:20px!important;line-height:1.15!important}.cfHome2Head p{font-size:11px!important;margin-top:3px!important}.cfHome2Sync{font-size:0!important;width:42px;height:42px;padding:0!important;border-radius:12px!important}.cfHome2Sync:before{content:'↻';font-size:21px}.cfHome2Kpis{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important}.cfHCard{min-height:86px!important;padding:11px!important;border-radius:14px!important}.cfHCard:first-child{grid-column:1/-1;min-height:90px!important}.cfHLabel{font-size:9.5px!important}.cfHValue{font-size:19px!important;margin-top:6px!important;letter-spacing:-.02em}.cfHCard:first-child .cfHValue{font-size:24px!important}.cfHSub{font-size:10px!important;margin-top:5px!important}.cfHome2Grid{display:block!important;margin-top:9px!important}.cfHPanel{padding:0!important;border-radius:15px!important;margin-bottom:9px!important;overflow:hidden}.cfHPanel>h3,.cfHPanel>p{margin-left:13px!important;margin-right:52px!important}.cfHPanel>h3{padding-top:13px!important;font-size:14px!important}.cfHPanel>p{font-size:10.5px!important;margin-bottom:11px!important}.cfHPanel.cfmCollapsed>*:not(h3):not(p):not(.cfmCollapse){display:none!important}.cfHPanel.cfmCollapsed{min-height:62px}.cfmCollapse{position:absolute;right:12px;top:12px;width:34px;height:34px;border:1px solid var(--cfm-line)!important;background:#faf8f6!important;border-radius:10px!important;padding:0!important;color:#5d514a!important;font-size:17px!important;line-height:1!important}.cfHPanel{position:relative}.cfGoalTop,.cfGoalBar,.cfGoalStats,.cfHome2Note,.cfOps,.cfAgendaBtn{margin-left:13px!important;margin-right:13px!important}.cfGoalStats{grid-template-columns:1fr 1fr!important;gap:7px!important}.cfGoalStats div:last-child{grid-column:1/-1}.cfOps{grid-template-columns:repeat(3,1fr)!important;gap:6px!important}.cfOps div{padding:9px 7px!important}.cfOps b{font-size:16px!important}.cfAgendaBtn{width:calc(100% - 26px)!important;margin-bottom:13px!important}.cfHome2Note{margin-bottom:13px!important}
/* cartões e tabelas legíveis no restante do app */
.dataCard,.card,.kpiCard{border-radius:14px!important}.kpis{gap:8px!important}.tableWrap,.tablewrap,[class*="table-wrap"]{overflow-x:auto!important;-webkit-overflow-scrolling:touch}.modalbox{width:calc(100vw - 18px)!important;max-width:none!important;max-height:92vh!important;border-radius:18px!important}.modal{padding:9px!important}.actions{flex-wrap:wrap!important}.actions button{min-height:42px}.field input,.field select,.field textarea,input,select,textarea{font-size:16px!important}
/* esconde a fileira de navegação desktop apenas se a detectarmos com segurança */
.cfmDesktopNavHidden{display:none!important}
}
`;document.head.appendChild(s)}
const icons={home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/></svg>',agenda:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/></svg>',money:'<svg viewBox="0 0 24 24"><path d="M4 7h16v12H4z"/><path d="M7 4h10M8 13h8M12 9v8"/></svg>',clients:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3.5 20c.5-4 2.5-6 5.5-6s5 2 5.5 6"/><path d="M16 8.5c2 .2 3.5 1.8 3.5 3.7M16 15c2.6.3 4 1.9 4.5 5"/></svg>',more:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></svg>'};
function clickByText(words){const els=[...document.querySelectorAll('button,a,[role="tab"]')].filter(e=>!e.closest('#cfMobileNav,#cfMobileSheet'));for(const w of words){const el=els.find(e=>e.textContent.trim().toLowerCase().includes(w.toLowerCase()));if(el){el.click();return true}}return false}
function openAgenda(){if(typeof window.openFinancialAgenda==='function'){window.openFinancialAgenda();return}if(typeof window.openExpenseCalendar==='function'){window.openExpenseCalendar();return}clickByText(['calendário','agenda'])}
function nav(action){closeMore();if(action==='home')clickByText(['início']);else if(action==='agenda')openAgenda();else if(action==='finance')clickByText(['financeiro']);else if(action==='clients')clickByText(['alunos','clientes']);setActive(action)}
function setActive(a){document.querySelectorAll('.cfmNavBtn').forEach(b=>b.classList.toggle('active',b.dataset.action===a))}
function more(){document.getElementById('cfMobileSheet')?.classList.add('open');document.getElementById('cfMobileBackdrop')?.classList.add('open')}
function closeMore(){document.getElementById('cfMobileSheet')?.classList.remove('open');document.getElementById('cfMobileBackdrop')?.classList.remove('open')}
window.cfmNav=nav;window.cfmMore=more;window.cfmClose=closeMore;window.cfmOpen=function(key){closeMore();const map={billing:['cobrança'],calendar:['calendário'],holidays:['feriados'],reports:['relatórios'],settings:['configurações']};clickByText(map[key]||[key])};
function buildNav(){if(!document.body||document.getElementById('cfMobileNav'))return;const n=document.createElement('nav');n.id='cfMobileNav';n.setAttribute('aria-label','Navegação principal');n.innerHTML=`<button class="cfmNavBtn active" data-action="home" onclick="cfmNav('home')">${icons.home}<span>Início</span></button><button class="cfmNavBtn" data-action="agenda" onclick="cfmNav('agenda')">${icons.agenda}<span>Agenda</span></button><button class="cfmNavBtn" data-action="finance" onclick="cfmNav('finance')">${icons.money}<span>Financeiro</span></button><button class="cfmNavBtn" data-action="clients" onclick="cfmNav('clients')">${icons.clients}<span>Clientes</span></button><button class="cfmNavBtn" data-action="more" onclick="cfmMore()">${icons.more}<span>Mais</span></button>`;document.body.appendChild(n);const back=document.createElement('div');back.id='cfMobileBackdrop';back.onclick=closeMore;document.body.appendChild(back);const sh=document.createElement('aside');sh.id='cfMobileSheet';sh.innerHTML=`<div class="cfmGrab"></div><div class="cfmSheetHead"><strong>Mais opções</strong><button class="cfmClose" onclick="cfmClose()">×</button></div><div class="cfmSheetGrid"><button class="cfmMore" onclick="cfmOpen('billing')"><span>▣</span>Cobrança</button><button class="cfmMore" onclick="cfmOpen('calendar')"><span>▦</span>Calendário</button><button class="cfmMore" onclick="cfmOpen('holidays')"><span>★</span>Feriados</button><button class="cfmMore" onclick="cfmOpen('reports')"><span>↗</span>Relatórios</button><button class="cfmMore" onclick="cfmOpen('settings')"><span>⚙</span>Configurações</button></div>`;document.body.appendChild(sh)}
function collapsibles(){document.querySelectorAll('.cfHome2 .cfHPanel').forEach((p,i)=>{if(p.querySelector('.cfmCollapse'))return;const b=document.createElement('button');b.className='cfmCollapse';b.setAttribute('aria-label','Recolher seção');b.textContent='⌃';b.onclick=()=>{const c=p.classList.toggle('cfmCollapsed');b.textContent=c?'⌄':'⌃';b.setAttribute('aria-label',c?'Expandir seção':'Recolher seção');try{localStorage.setItem('cfm-panel-'+i,c?'1':'0')}catch(_){}};p.appendChild(b);try{if(localStorage.getItem('cfm-panel-'+i)==='1'){p.classList.add('cfmCollapsed');b.textContent='⌄'}}catch(_){}})}
function hideDesktopNav(){if(!isMobile())return;const labels=['Início','Cobrança','Alunos','Calendário','Financeiro','Feriados','Relatórios','Configurações'];[...document.querySelectorAll('nav,.tabs,.tabbar')].forEach(el=>{const t=el.textContent||'';if(labels.filter(x=>t.includes(x)).length>=5&&!el.closest('#cfMobileNav,#cfMobileSheet'))el.classList.add('cfmDesktopNavHidden')})}
function install(){addCss();buildNav();collapsibles();hideDesktopNav()}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{if(isMobile()){collapsibles();hideDesktopNav()}},80)}).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',install);install();matchMedia(MOBILE).addEventListener?.('change',install);
})();