(()=>{'use strict';
const URL='https://yjpxjzgvshaabjpdpbsc.supabase.co';
const KEY='sb_publishable_cfk3k9kcgmbvUp-oUmoNfw_rYLUzIge';
const sb=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,workspace:null,member:null,profile:null,clients:[],services:[],appointments:[],charges:[],payments:[],expenses:[]};
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n||0));
const localDate=d=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(d||new Date());
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(msg,error=false){const t=$('#toast');t.textContent=msg;t.className='toast show'+(error?' error':'');setTimeout(()=>t.className='toast',2600)}
function view(name){['authView','onboardingView','appView'].forEach(id=>$('#'+id).classList.toggle('hidden',id!==name))}
async function q(table,build){let req=sb.from(table).select('*');if(build)req=build(req);const {data,error}=await req;if(error)throw error;return data||[]}
async function loadContext(){
 const {data:{user}}=await sb.auth.getUser();state.user=user;if(!user){view('authView');return}
 const memberships=await q('workspace_members',x=>x.eq('user_id',user.id).eq('status','active').limit(1));
 if(!memberships.length){view('onboardingView');return}
 state.member=memberships[0];const ws=await q('workspaces',x=>x.eq('id',state.member.workspace_id).limit(1));state.workspace=ws[0];
 const pp=await q('professional_profiles',x=>x.eq('workspace_id',state.workspace.id).eq('user_id',user.id).limit(1));state.profile=pp[0]||null;view('appView');await refresh();
}
async function refresh(){const w=state.workspace.id;const [clients,services,appointments,charges,payments,expenses]=await Promise.all([
 q('clients',x=>x.eq('workspace_id',w).order('display_name')),
 q('services',x=>x.eq('workspace_id',w).eq('active',true).order('name')),
 q('appointments',x=>x.eq('workspace_id',w).order('starts_at',{ascending:false}).limit(100)),
 q('charges',x=>x.eq('workspace_id',w).order('due_date',{ascending:false}).limit(100)),
 q('saas_payments',x=>x.eq('workspace_id',w).order('paid_at',{ascending:false}).limit(100)),
 q('saas_expenses',x=>x.eq('workspace_id',w).order('created_at',{ascending:false}).limit(100))]);
 Object.assign(state,{clients,services,appointments,charges,payments,expenses});render();
}
function render(){
 $('#workspaceName').textContent=state.workspace?.name||'Meu espaço';const name=state.profile?.display_name||state.user?.email?.split('@')[0]||'';$('#helloName').textContent='Olá, '+name;
 $('#todayLabel').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}).format(new Date());
 const prof=(state.profile?.profession||'').toLowerCase();$('#clientsTitle').textContent=/psic|méd|medic|fisio|terap|nutri/.test(prof)?'Pacientes':'Clientes';
 const now=new Date(), y=now.getFullYear(),m=now.getMonth();const inMonth=x=>{const d=new Date(x);return d.getFullYear()===y&&d.getMonth()===m};
 const received=state.payments.filter(x=>inMonth(x.paid_at)).reduce((a,x)=>a+Number(x.amount),0);const pending=state.charges.filter(x=>['pending','partial','overdue'].includes(x.status)).reduce((a,x)=>a+Number(x.amount),0);const expenses=state.expenses.filter(x=>inMonth(x.paid_at||x.created_at)&&x.status!=='cancelled').reduce((a,x)=>a+Number(x.amount),0);const appts=state.appointments.filter(x=>inMonth(x.starts_at));
 $('#monthBalance').textContent=money(received-expenses);$('#mReceived').textContent=$('#fReceived').textContent=money(received);$('#mPending').textContent=$('#fPending').textContent=money(pending);$('#mExpenses').textContent=$('#fExpenses').textContent=money(expenses);$('#mAppointments').textContent=appts.length;$('#fResult').textContent=money(received-expenses);
 const today=localDate();const ta=state.appointments.filter(x=>localDate(new Date(x.starts_at))===today).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at));
 list('#todayAppointments',ta.map(a=>appointmentRow(a,true)),'Nenhum atendimento hoje.');list('#appointmentsList',state.appointments.slice().sort((a,b)=>new Date(b.starts_at)-new Date(a.starts_at)).map(a=>appointmentRow(a,false)),'Nenhum atendimento cadastrado.');
 list('#clientsList',state.clients.map(c=>`<div class="row"><div class="logo small">${esc(c.display_name).slice(0,2).toUpperCase()}</div><div><strong>${esc(c.display_name)}</strong><small>${esc(c.email||c.phone||'Sem contato')}</small></div><span class="pill ${c.status==='active'?'ok':''}">${c.status==='active'?'Ativo':'Inativo'}</span></div>`),'Nenhum cliente cadastrado.');
 list('#chargesList',state.charges.map(c=>`<div class="row"><div class="time">${money(c.amount)}</div><div><strong>${esc(c.description)}</strong><small>Vence ${new Date(c.due_date+'T12:00:00').toLocaleDateString('pt-BR')}</small></div><span class="pill ${c.status==='paid'?'ok':c.status==='overdue'?'danger':''}">${esc(c.status)}</span></div>`),'Nenhuma cobrança.');
 list('#expensesList',state.expenses.map(e=>`<div class="row"><div class="time">${money(e.amount)}</div><div><strong>${esc(e.description)}</strong><small>${esc(e.category||'Despesa')}</small></div><span class="pill ${e.status==='paid'?'ok':''}">${esc(e.status)}</span></div>`),'Nenhuma despesa.');
 const tf=[...state.payments.filter(x=>localDate(new Date(x.paid_at))===today).map(x=>({t:'Entrada',v:x.amount})),...state.expenses.filter(x=>x.paid_at&&localDate(new Date(x.paid_at))===today).map(x=>({t:'Saída',v:-Number(x.amount)}))];list('#todayFinance',tf.map(x=>`<div class="row"><div class="time">${x.v>=0?'+':'−'}</div><div><strong>${esc(x.t)}</strong><small>${money(Math.abs(x.v))}</small></div><span class="pill ${x.v>=0?'ok':'danger'}">${money(x.v)}</span></div>`),'Nenhuma movimentação hoje.');
 $('#rClients').textContent=state.clients.filter(x=>x.status==='active').length;$('#rTicket').textContent=money(state.payments.length?state.payments.reduce((a,x)=>a+Number(x.amount),0)/state.payments.length:0);$('#rOverdue').textContent=money(state.charges.filter(x=>x.status==='overdue').reduce((a,x)=>a+Number(x.amount),0));$('#rCompleted').textContent=state.appointments.filter(x=>x.status==='completed').length;
}
function appointmentRow(a,compact){const c=state.clients.find(x=>x.id===a.client_id);const d=new Date(a.starts_at);return `<div class="row"><div class="time">${d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</div><div><strong>${esc(c?.display_name||'Cliente')}</strong><small>${compact?'Hoje':d.toLocaleDateString('pt-BR')} · ${esc(a.status)}</small></div><span class="pill ${a.status==='completed'?'ok':a.status==='cancelled'?'danger':''}">${esc(a.status)}</span></div>`}
function list(sel,rows,empty){const el=$(sel);el.innerHTML=rows.length?rows.join(''):`<div class="empty">${empty}</div>`}
let authMode='login';$('#authToggle').onclick=()=>{authMode=authMode==='login'?'signup':'login';$('#authTitle').textContent=authMode==='login'?'Entrar':'Criar conta';$('#authSubmit').textContent=authMode==='login'?'Entrar':'Criar conta';$('#authToggle').textContent=authMode==='login'?'Criar uma conta':'Já tenho uma conta'};
$('#authForm').onsubmit=async e=>{e.preventDefault();try{const email=$('#authEmail').value.trim(),password=$('#authPassword').value;const r=authMode==='login'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});if(r.error)throw r.error;if(authMode==='signup'&&!r.data.session){toast('Confira seu e-mail para confirmar a conta.');return}await loadContext()}catch(err){toast(err.message,true)}};
$('#onboardingForm').onsubmit=async e=>{e.preventDefault();try{const name=$('#onboardName').value.trim(),profession=$('#onboardProfession').value,business=$('#onboardBusiness').value.trim()||name;const {data:w,error:we}=await sb.from('workspaces').insert({name:business,slug:null}).select().single();if(we)throw we;const {error:me}=await sb.from('workspace_members').insert({workspace_id:w.id,user_id:state.user.id,role:'owner',status:'active'});if(me)throw me;const terminology=/Personal/i.test(profession)?{client:'Aluno',appointment:'Aula'}:{client:'Paciente',appointment:/Médico/i.test(profession)?'Consulta':'Sessão'};const {error:pe}=await sb.from('professional_profiles').insert({workspace_id:w.id,user_id:state.user.id,display_name:name,profession,terminology});if(pe)throw pe;toast('Espaço criado.');await loadContext()}catch(err){toast(err.message,true)}};
$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
function go(page){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+page+'Page').classList.add('active');$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent={home:'Início',agenda:'Agenda',clients:'Clientes',finance:'Financeiro',reports:'Relatórios'}[page];$('.sidebar').classList.remove('open')}
$$('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-goto]').forEach(b=>b.onclick=()=>go(b.dataset.goto));
const fields={client:()=>`<label>Nome<input name="display_name" required></label><label>E-mail<input name="email" type="email"></label><label>Telefone<input name="phone"></label>`,appointment:()=>`<label>Cliente<select name="client_id" required><option value="">Selecione</option>${state.clients.filter(x=>x.status==='active').map(x=>`<option value="${x.id}">${esc(x.display_name)}</option>`).join('')}</select></label><label>Início<input name="starts_at" type="datetime-local" required></label><label>Duração (min)<input name="duration" type="number" value="60" min="5"></label><label>Valor<input name="price" type="number" step="0.01" min="0"></label>`,charge:()=>`<label>Descrição<input name="description" required></label><label>Valor<input name="amount" type="number" step="0.01" min="0" required></label><label>Vencimento<input name="due_date" type="date" required></label>`,expense:()=>`<label>Descrição<input name="description" required></label><label>Valor<input name="amount" type="number" step="0.01" min="0" required></label><label>Categoria<input name="category"></label><label>Vencimento<input name="due_date" type="date"></label>`};
let action='client';function openModal(a){action=a;$('#modalTitle').textContent={client:'Novo cliente',appointment:'Novo atendimento',charge:'Nova cobrança',expense:'Nova despesa'}[a];$('#modalFields').innerHTML=fields[a]();$('#modal').showModal()}
$$('[data-action]').forEach(b=>b.onclick=()=>openModal(b.dataset.action));$('#quickAdd').onclick=()=>openModal('appointment');
$('#modalForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();try{const fd=Object.fromEntries(new FormData(e.currentTarget));const w=state.workspace.id;let res;if(action==='client')res=await sb.from('clients').insert({workspace_id:w,display_name:fd.display_name,email:fd.email||null,phone:fd.phone||null});if(action==='appointment'){const start=new Date(fd.starts_at),end=new Date(start.getTime()+Number(fd.duration||60)*60000);res=await sb.from('appointments').insert({workspace_id:w,client_id:fd.client_id,starts_at:start.toISOString(),ends_at:end.toISOString(),price:fd.price?Number(fd.price):null});}if(action==='charge')res=await sb.from('charges').insert({workspace_id:w,description:fd.description,amount:Number(fd.amount),due_date:fd.due_date});if(action==='expense')res=await sb.from('saas_expenses').insert({workspace_id:w,description:fd.description,amount:Number(fd.amount),category:fd.category||null,due_date:fd.due_date||null});if(res?.error)throw res.error;$('#modal').close();toast('Salvo com sucesso.');await refresh()}catch(err){toast(err.message,true)}});
sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session)setTimeout(loadContext,0)});loadContext().catch(e=>{console.error(e);toast('Não foi possível carregar o CoachFlow.',true)});
})();